# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  show:
    runs-on: ubuntu-latest
    steps:
    - name: checkout enviroment
      uses: actions/checkout@v3

    - name: show enviroment
      run: |
        ls -la && ls -la ./*
