name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  show:
    runs-on: ubuntu-latest
    steps:
    - name: checkout enviroment
      uses: actions/checkout@v3

    - name: show enviroment
      run: |
        ls -la && ls -la ./*
